version: "3.7"

services:
  frontend:
    build: ./1cs-frontend
    depends_on:
      - backend
    volumes:
      - ./1cs-frontend/src:/app/src
    ports:
      - "8000:8000"
      
  backend:
    build:
      context: ./1cs-backend
      dockerfile: Dockerfile.dev
    depends_on:
      - mysqldb 
    volumes:
      - ./1cs-backend/src:/app/src
    ports:
      - "5000:5000"
      
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
      
  mysqldb:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=p@ssw0rd1
    ports:
      - "3306:3306"
      
  pyselenium:
    build: ./pyselenium-user
    depends_on:
      - firefox
      - frontend
    volumes:
      - ./pyselenium/src:/app/src
      
  firefox:
    image: selenium/node-firefox:4.0.0-beta-1-20210215
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    ports:
      - "6902:5900"
      
  selenium-hub:
    image: selenium/hub:4.0.0-beta-1-20210215
    container_name: selenium-hub
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
      
  office:
    image: libreoffice/online
    environment:
      - username=admin
      - password=admin
      - DONT_GEN_SSL_CERT=1
      - extra_params=--o:ssl.enable=false
    ports:
      - "9980:9980"
  
  
