version: "3.7"

services:
  frontend:
    build: ./1cs-frontend
    depends_on:
      - backend
    volumes:
      - ./1cs-frontend/src:/app/src
    ports:
      - "8000:8000"

  backend:
    build:
      context: ./1cs-backend
      dockerfile: Dockerfile.dev
    depends_on:
      - db
    volumes:
      - ./1cs-backend/src:/app/src
    ports:
      - "5000:5000"

  adminer:
    image: adminer
    restart: always
    ports:
      - "8090:8080"

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    cap_add:
      - SYS_NICE  # CAP_SYS_NICE
    environment:
      - MYSQL_ROOT_PASSWORD=p@ssw0rd1
      - MYSQL_PASSWORD=p@ssw0rd1
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
    ports:
      - "3306:3306"

  nextcloud:
    image: nextcloud
    restart: always
    ports:
      - "8080:80"

  pyselenium-admin:
    build: ./pyselenium-admin
    depends_on:
      - nextcloud
      - firefox-1

  pyselenium-employee:
    build: ./pyselenium-employee
    depends_on:
      - firefox-2
      - frontend

  firefox-1:
    image: selenium/node-firefox:4.0.0-beta-3-prerelease-20210402
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    ports:
      - "6901:5900"
      - "7901:7900"

  firefox-2:
    image: selenium/node-firefox:4.0.0-beta-3-prerelease-20210402
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    ports:
      - "6902:5900"
      - "7902:7900"

  selenium-hub:
    image: selenium/hub:4.0.0-beta-3-prerelease-20210402
    container_name: selenium-hub
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
  
