FROM node:alpine # The minimal baseline we need for Nodejs
WORKDIR /app

# copy the package.json file, update any dependencies and install them
COPY package.json .
RUN npm update
RUN npm install

# copy the whole source folder (the dir is relative to the Dockerfile
COPY . .

CMD [ "npm", "run", "start" ]
