# From this article: https://wkrzywiec.medium.com/build-and-run-angular-application-in-a-docker-container-b65dbbc50be8
# And this tutorial: https://www.youtube.com/watch?v=etA5xiX5TCA

# Stage 1: build
FROM node:latest AS node
WORKDIR /app
COPY . .
RUN npm install
RUN npm run build

# Stage 2: run
FROM nginx:alpine
COPY --from=node /app/dist/landing /usr/share/nginx/html
